name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Python 3.11.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'
  
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
  
      - name: Install dependencies
        run: pip install -r ./api/requirements.txt

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_OCEAN_04915D20F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "./api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          REACT_APP_B2C_CLIENT_ID: ${{ secrets.REACT_APP_B2C_CLIENT_ID }}
          REACT_APP_B2C_TENANT: ${{ secrets.REACT_APP_B2C_TENANT }}
          REACT_APP_B2C_TENANT_ID: ${{ secrets.REACT_APP_B2C_TENANT_ID }}
          REACT_APP_B2C_USER_FLOW: ${{ secrets.REACT_APP_B2C_USER_FLOW }}
          REACT_APP_AZURE_REGION: ${{ secrets.REACT_APP_AZURE_REGION }}
          REACT_APP_AZURE_SPEECH_KEY: ${{ secrets.REACT_APP_AZURE_SPEECH_KEY}}
          REACT_APP_API_BASE_URL: ${{secrets.REACT_APP_API_BASE_URL}}
          REACT_APP_STRIPE_PUBLIC_KEY: ${{secrets.REACT_APP_STRIPE_PUBLIC_KEY}}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_OCEAN_04915D20F }}
          action: "close"
